import "./globals.css";
import Header from "./components/Header";
import HeroSec from "./components/HeroSec";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="">
        <Header />
        
        {children}
      </body>
    </html>
  );
}
